# Generated by Django 5.1.4 on 2025-06-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('mobileNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateField()),
                ('country', models.CharField(choices=[('IND', 'INDIA'), ('US', 'UNITED STATES'), ('UK', 'UNITED KINGDOM'), ('MEX', 'MEXICO'), ('CHN', 'CHINA'), ('PAK', 'PAKISTAN'), ('AFG', 'AFGANISTAN'), ('ALG', 'ALGERIA'), ('INA', 'INDONESIA'), ('IRN', 'IRAN'), ('QTR', 'QATAR'), ('RUS', 'RUSSIA'), ('SPN', 'SPAIN'), ('TURK', 'TURKEY'), ('AUS', 'AUSTRALIA'), ('BRZ', 'BRAZIL'), ('FRANCE', 'FRANCE'), ('GER', 'GERMANY'), ('JPN', 'JAPAN'), ('PL', 'PALESTINE'), ('YEMEN', 'YEMEN')], max_length=30)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
